### ISSUE TITLE
4.19.3 @arcgis/core ES modules: ScaleBar does not support spatial reference (wkid 4269)

### ISSUE THREAD

**Issue by bsanti** [Esri/jsapi-resources#296] opened 2021-05-12 21:05 UTC
When attempting to add a ScaleBar widget to a MapImageLayer that points to a MapServer with wkid 4269 the widget does not render and the following error shows in browser debug console:

_message: "the input geometries spatial reference is not supported"_

Please use following github repo to recreate:
https://github.com/bsanti/angularScaleBar

I am reporting an issue with 

- [x ] TypeScript definitions
- [ ] another resource in this repository

**Comment by bsanti** [comment] 2021-05-12 21:06
wkid 4269 is valid based on esri documentation

**Comment by andygup** [comment] 2021-05-13 16:24
@bsanti Be sure to set a basemap [here](https://github.com/bsanti/angularScaleBar/blob/master/app/app.component.ts#L27). This codepen shows the Census MapImageLayer working okay: https://codepen.io/andygup/pen/poeyJpO?editors=1000.

**Comment by bsanti** [comment] 2021-05-13 20:45
hi @andygup, I did not have to specify a basemap to render the ScaleBar widget in previous versions when working exclusively with MapImageLayer.  The sample you provided renders the ScaleBar without a basemap if you use v4.18.  I noticed other map coordinate systems (ex wkid 4326) work without a basemap when using v4.19.  Please advise.

**Comment by NoashX** [comment] 2021-05-13 22:11
Hi @bsanti, thanks for reporting this. It looks like an issue on our side, but we are still investigating. In the meantime, we have a workaround where if you define the MapView extent and spatial reference, then this will work at 4.19. Here is an example app that shows this: https://codepen.io/noash/pen/gOmrwKb?editors=1000

**Comment by bsanti** [comment] 2021-05-26 14:04
Although specifying a different spatial reference id when instantiating MapView is a workaround for the [Census Map Server](https://sampleserver6.arcgisonline.com/arcgis/rest/services/Census/MapServer), this does not work for my private MapServer.  I still get a similar error: incompatible spatialReference {"wkid":4269} with view's spatialReference {"wkid":4326}

**Comment by NoashX** [comment] 2021-06-08 16:27
Hi @bsanti, we confirmed that we have a fix for this for 4.20. We expect 4.20 to release layer this month or early July.

**Closed** 2021-06-08 16:28 UTC
