### ISSUE TITLE
Bug:  webpack build custom widget throw error

### ISSUE THREAD

**Issue by webmapLee** [Esri/jsapi-resources#414] opened 2022-05-17 16:37 UTC
webpack package version:
"webpack": "^5.72.1",
"webpack-cli": "^4.9.2",
"webpack-dev-server": "^4.9.0"

webpack.config .js:
`const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const path = require('path');
module.exports = {
    entry: './src/index.ts',
    output: {
        path: __dirname + '/dist',
    },
    module: {
        rules: [
            {
                test: /\.tsx?$/,
                use: 'ts-loader',
                exclude: /node_modules/,
            },{
                test: /\.css$/,
                use:[
                    {
                        loader:MiniCssExtractPlugin.loader,
                    },
                    {
                        loader:'css-loader',
                        options:{

                        }
                    },{
                        loader:'postcss-loader',
                    }
                ]
            }
        ]
    },
    devServer: {
        // contentBase: './dist',
        liveReload:true,
        compress: true,
        port: 9000,
        open: true,
    },
    plugins:[
        new MiniCssExtractPlugin(),
        new HtmlWebpackPlugin({
            template:'./src/index.html',
        })
    ],
    resolve: {
        extensions: ['.tsx', '.ts', '.js']
    }
}`

widget.tsx:
`import { subclass} from "@arcgis/core/core/accessorSupport/decorators";

import { tsx} from "@arcgis/core/widgets/support/widget";
import Widget from "@arcgis/core/widgets/Widget";
@subclass("esri.widgets.HelloWorld")
class HelloWorld extends Widget {
  render() {
    return (
      <div>John Smith</div>
    );
  }
}
export default HelloWorld;`

erros:
![image](https://user-images.githubusercontent.com/20334500/168863344-a0315474-4dcf-47a4-bea7-853e883b3787.png)
![image](https://user-images.githubusercontent.com/20334500/168863424-aac4aa41-eb30-434f-91e9-cbb200cba75b.png)

**Comment by andygup** [comment] 2022-05-17 16:49
Hi @webmapLee please provide a link to a simple github repo that reproduces the error.

**Comment by webmapLee** [comment] 2022-05-17 16:58
https://github.com/webmapLee/arcgis_webpack.git

**Comment by andygup** [comment] 2022-05-17 17:21
Thanks, it seems to be related to the TypeScript configuration, it's not a problem with the ArcGIS API for JavaScript. 

Try adjusting the target and module settings in `tsconfig.json`, the following worked for me:

```json
        "target": "ES2020",
        "module": "ESNext",
```

**Comment by andygup** [comment] 2022-05-17 19:12
Glad it's working. I'm not sure happened, that is a common TypeScript configuration error. I'll go ahead and close the issue.

**Closed by andygup** 2022-05-17 19:12 UTC
