### ISSUE TITLE
@arcgis/core with angular 11 gives unpredictable results

### ISSUE THREAD

**Issue by bishrant** [Esri/jsapi-resources#252] opened 2021-01-21 16:48 UTC
Migrating our app from arcgis-js-api 4.17 to @arcgis/core using angular 11 is giving unpredictable results.

Target on tsconfig.json
ES5: App compiles but WebMaps and MapImageLayer are not loading, drawing works fine

ES6/ES2015: App Compiles but drawing does not show up on first, Shows up only if you zoom in. Works fine on second time. See attached gif.
![es6](https://user-images.githubusercontent.com/4143738/105382648-ebf81d80-5bd5-11eb-9d09-dfbeb8b6a519.gif)

ES 2019: Same as ES6.

Please see [https://github.com/bishrant/jsapi-angular-cli](https://github.com/bishrant/jsapi-angular-cli) for a reproducible example. JSAPI resources esm samples were used as starting ground.

I am reporting an issue with 

- [ ] TypeScript definitions
- [ x] another resource in this repository

**Comment by andygup** [comment] 2021-01-21 17:16
Thanks @bishrant for letting us know, and sorry for the inconvenience. This is a known issue: https://github.com/Esri/jsapi-resources/issues/240#issuecomment-756827160. We hope to have it fixed in the 4.19 release (April). 

Since this is a regression, potential temporary workarounds include sticking with version 4.17 using esri-loader or arcgis-webpack-plugin.

I'll go ahead and close this issue.

**Closed by andygup** 2021-01-21 17:16 UTC
