### ISSUE TITLE
Angular with 4.18 - First geometry drawn with sketch widget are not immediately visible unless view level changes

### ISSUE THREAD

**Issue by josiahpeters** [Esri/jsapi-resources#240] opened 2021-01-06 16:21 UTC
I am reporting an issue with 

- [ ] TypeScript definitions
- [x] another resource in this repository

Issue is with [Angular CLI Example ](https://github.com/Esri/jsapi-resources/tree/master/esm-samples/jsapi-angular-cli).

The first geometry that is drawn using the sketch widget is not visible until you change zoom levels. The transform handles are not visible either. However if you mouse over them they appear. 

The shape is visible once you change zoom levels.

Geometries drawn after the first one do not exhibit this issue shapes do not have this issue.

Here is a recording of the defect in action:
https://user-images.githubusercontent.com/446011/103791789-1b1c6580-5000-11eb-8186-7a59f2ed76a9.mp4

**Comment by josiahpeters** [comment] 2021-01-06 16:26
I forked the repo and created a branch that reproduces this issue: https://github.com/josiahpeters/jsapi-resources/blob/issue/240/esm-samples/jsapi-angular-cli/src/app/app.component.ts

**Comment by andygup** [comment] 2021-01-07 18:22
@josiahpeters thanks for reporting. I was able to reproduce the bug, it looks like a regression at 4.18. We are investigating further.

**Comment by josiahpeters** [comment] 2021-01-08 02:49
@andygup thanks for looking into this. I was eager to port our Angular application from 4.17 using the esri-loader to the new module loading for 4.18 and ran into this blocker. Is this something that would be addressed in a incremental/patch release or should I expect to wait until 4.19? At first glance it looks like you're on a monthly release cadence? I'm not looking for a commitment, but just planning when I should come back to the esm implementation.

Thanks again.

**Comment by andygup** [comment] 2021-01-08 15:47
Thanks for the all the detailed information that was very helpful. We certainly understand the eagerness to port over to ES Modules! We are releasing four times a year, and we are looking at fixing this in 4.19 (April). Also note, at some point soon you'll be able to retest ES Modules using /next: https://github.com/Esri/feedback-js-api-next#npm.

I'll go ahead and close this issue since we have logged the bug.

**Closed by andygup** 2021-01-08 15:47 UTC

**Comment by andygup** [comment] 2021-02-24 16:44
@josiahpeters we believe we fixed this bug. Can you retest using `npm install @arcgis/core@next`?

**Comment by BillClyde** [comment] 2021-03-08 18:30
@andygup I ran into this in 4.18.1 and re-tested with 4.19. I can confirm that it is fixed.

**Comment by andygup** [comment] 2021-03-08 19:00
Sweet! Thanks for the update.

**Comment by josiahpeters** [comment] 2021-03-09 04:46
> @josiahpeters we believe we fixed this bug. Can you retest using `npm install @arcgis/core@next`?

I have confirmed this is fixed in the sample repository I opened up an issue with. I also confirmed this is working as expected in the code my employer is waiting to upgrade until this defect is fixed. 

Thank you, @andygup!
