### ISSUE TITLE
4.28.10 @arcgis/core ES modules: Popup trigger-action does not execute after ActionButton disable\enable toggle

### ISSUE THREAD

**Issue by bsanti** [Esri/jsapi-resources#502] opened 2024-02-14 17:07 UTC
### IMPORTANT

- [X] My question is related to the samples and content within this repository. For all other issues, open a ticket with [Esri Technical Support](https://support.esri.com/) or post your question in the [community forum](https://community.esri.com/t5/arcgis-api-for-javascript/ct-p/arcgis-api-for-javascript).
- [X] I have [checked for existing issues](https://github.com/Esri/jsapi-resources/issues) to avoid duplicates. If someone has already opened an issue for what you are experiencing, please add a 👍 reaction and comment as necessary to the existing issue instead of creating a new one. You can also refer to this repo's [troubleshooting guide](../../TROUBLESHOOTING.md) for hints and suggestions.

### Actual behavior

It appears that the Popup trigger-action is no longer firing after an ActionButton is disabled and then enabled.  The sample project will write the action id to the console when the trigger action is executed.
I have disregarded NG05104 error on load of the page as I dont feel it has to do with the issue with the action button

### Expected behavior

The trigger-action should continue to fire after an ActionButton disable/enable

### Reproduction sample

https://github.com/bsanti/actionbutton.git

### Reproduction steps

1. Follow readme to build and serve the application
2. Click "Show Popup" button, Popup renders
3. Click Action Button with ? icon, console logs ActionButton id
4. Click "Disable Action" button, button is disabled as expected
5. Click "Enable Action" button, button is enabled as expected
6. Click Action Button with ? icon, console no longer logs ActionButton id

### Reproduction browser

Chrome 121.0.6167.86

### Operating System (check https://whatsmyos.com)

-OS: Windows 10 Enterprise, Version: 22H2, OS Build: 19045.3930
-Device: DELL Precision 7540

**Comment by lboyd93** [comment] 2024-02-14 21:02
Hi @bsanti -

This doesn't seem to be an issue with the API since it doesn't reproduce in a plain vanilla JS application on macOS or Windows 10 Enterprise with Chrome or Firefox so this could be a different problem related to Angular: https://codepen.io/laurenb14/pen/gOEZoVw?editors=1000
1. Click the action button once the popup appears. This will trigger an alert from the "trigger-action" event handler. 
2. Close the alert, click the `Disable action` button to disable, then click `Enable action` to enable it again.
3. Click the action button in the popup and the alert should appear.

We would like to suggest you re-post your question on the community site: https://community.esri.com/t5/arcgis-javascript-maps-sdk-questions/bd-p/arcgis-api-for-javascript-questions and provide the simple, working example using Stackblitz, github or equivalent.

**Comment by bsanti** [comment] 2024-02-15 16:41
Hi lboyd93, thanks for the feedback, however, i believe this is an issue that can only be recreated using the ESModules.  It does not happen when using AMD modules via ArcGIS CDN.

I was able to verify this using the provided esri sample app @ https://github.com/Esri/jsapi-resources/tree/main/esm-samples/jsapi-angular-cli. In its current state (using ArcGis 4.28.x), the Popup trigger-action issue can be reproduced.  To isolate ArcGis 4.28.x and rule out Angular I reverted to previous ArcGis version:

./package.json: "@arcgis/core": 
	"~4.28.0" 
	modified to 
	"@arcgis/core": "~4.27.0"
./src/app/app.component.css: 
	@import 'https://js.arcgis.com/4.28/@arcgis/core/assets/esri/themes/light/main.css'; 
	modified to
	@import 'https://js.arcgis.com/4.27/@arcgis/core/assets/esri/themes/light/main.css';
	
When using ArcGis 4.27.x, the issue does not happen. This leads me to believe the issue started to occur in ArcGis 4.28.x.  When you get a chance would you please try it out to confirm?

Thanks!

**Comment by andygup** [comment] 2024-02-15 17:28
@bsanti thanks for the additional clarification, we'll reopen and take a closer look. To @lboyd93 point, we recommend posting all @arcgis/core API questions on the Esri Community site, it's much easier for others to search and find the information if they have a similar issue. This is only a samples repository with limited SEO.

**Comment by andygup** [comment] 2024-02-15 18:39
@bsanti we are unable to reproduce the issue using this repository's Angular sample + repurposing the Popup code from @lboyd93's [codepen](https://codepen.io/laurenb14/pen/gOEZoVw?editors=1000). I've attached our test project for your review. We recommend comparing our test sample with your code to see what might be breaking.

Test sample is using:
- @angular/cli@latest `17.2.0`
- @arcgis/core@rc (e.g. ` 4.29.0-next.20240215`)

[jsapi-angular-cli.zip](https://github.com/Esri/jsapi-resources/files/14300837/jsapi-angular-cli.zip)

**Comment by bsanti** [comment] 2024-02-16 02:21
Thanks @andygup , I was able to confirm the issue is not happening in the zip you provided which uses rc4.29 of @arcgis/core.  I was experiencing the issue in the current release (v4.28).  I will bring in the changes to my local project once 4.29 is released.

**Comment by bsanti** [comment] 2024-02-16 14:10
I brought in 4.29.0-next.20240215 into my workspace and it still was not working for me.  I agree with you that it does not appear to be @arcgis/core related at this point.  I will continue to troubleshoot on my end.  Thanks for your help on this.

**Comment by andygup** [comment] 2024-02-16 15:44
@bsanti it's possible you have a combination of dependencies in your project that are causing a zone.js issue. There's a known issue for some of the SDK widgets because of a Calcite bug, but usually those are easy to reproduce. You could try disabling zone.js monkey patching for `click` events. Further information and the steps for doing that are documented here:  https://github.com/Esri/jsapi-resources/tree/main/esm-samples/jsapi-angular-cli#known-issues.

**Comment by bsanti** [comment] 2024-02-16 18:03
@andygup I confirmed that the issue was due to the Calcite bug.  Thanks for pointing this out.  Looks like the @esri/calcite-components fix is scheduled for 2/27 maintenance release, my project has enough runway to hold off and consume it when available.  Thanks again.

**Comment by andygup** [comment] 2024-02-16 19:15
Thanks for confirming @bsanti. We'll go ahead and close this out as a [Known Issue](https://github.com/Esri/calcite-design-system/issues/7729).

**Closed by andygup** 2024-02-16 19:15 UTC
