### ISSUE TITLE
Angular 11 and @arcgis/core 4.18.1 fail to display features added from editor until zooming

### ISSUE THREAD

**Issue by sverkerEsriSE** [Esri/jsapi-resources#255] opened 2021-01-25 14:39 UTC
I am reporting an issue with 

- [ ] TypeScript definitions
- [x] another resource in this repository

# Issue
I'm with Esri Sweden support, and we've gotten report from a client that Angular 11 and JS API 4.18 is causing issues with rendering features when they are newly added to a web map. The feature, after being added, only appears after zooming in our out in the map.

# Replication
1. Clone the https://github.com/Esri/jsapi-resources repository
2. Move into the **jsapi-resources/esm-samples/jsapi-angular-cli** folder
3. Run _npm install_
4. Run _npm install -g @angular/cli_
5.
Now it's time to add some code:
###src/app/app.component.ts
change line 36 to the following:
`id: '6c5d657f1cb04a5eb78a450e3c699c2a',`

Add the following line after line 13:
`import Editor from '@arcgis/core/widgets/Editor'`

Around line 51, add the following:
`const editor = new Editor({
	view,
});`

And finally, after the following line:
`view.ui.add(bkExpand, 'top-right');`
Add the following:
`view.ui.add(editor, 'bottom-right');`

Save the edits

5. Run _ng serve --open_
6. Add a feature to the map from the editor dialog

Another example which doesn't use feature service
https://github.com/gurgelx/ArcGIS_example

**Comment by andygup** [comment] 2021-01-25 18:47
Thanks for reporting @sverkerEsriSE. We'll take a look. There a number of known issues with Angular 11 in 4.18.

**Comment by andygup** [comment] 2021-01-27 00:38
@sverkerEsriSE I was not able to reproduce the issue using the steps you described for jsapi-resources with dev or prod builds. I'm running Chrome (v88) on a Mac.

Did you see any errors in the browser console?

**Comment by gurgelx** [comment] 2021-01-27 08:06
@andygup Try the other example https://github.com/gurgelx/ArcGIS_example
1. clone it
2. npm install
3. ng serve --open

Should jump straight to the issue.
The map shows but no geometries renders until ju zoom-

**Comment by sverkerEsriSE** [comment] 2021-01-27 08:49
> @sverkerEsriSE I was not able to reproduce the issue using the steps you described for jsapi-resources with dev or prod builds. I'm running Chrome (v88) on a Mac.
> 
> Did you see any errors in the browser console?

No errors in the browser console.
I've tested with the following browsers on Windows 10 20H2:
- Microsoft Edge, v. 88.0.705
- Google Chrome v. 87.0.4280.141
- Google Chrome v. 88.0.4324.104
![Gif showing problem](https://content.screencast.com/users/SverkerEsri/folders/Default/media/5f02adad-1a68-4152-86a5-07fc1b6caddb/Problem_Angular_JSAPI418.gif)

**Comment by andygup** [comment] 2021-01-27 19:42
Got it. I was able to reproduce it using https://github.com/gurgelx/ArcGIS_example which implements `SketchViewModel`. This definitely looks like a known bug that we are investigating. Hopefully we can get this resolved for the 4.19 release in April.

I'll add your use case to the bug report and close this out. Thanks for reporting!

**Closed by andygup** 2021-01-27 19:42 UTC

**Comment by bsanti** [comment] 2021-02-18 03:41
Looking forward to this fix as well so I can use the latest bits.  I just tried the [dev snapshot of 4.19](https://github.com/Esri/feedback-js-api-next) and the issue is still present but I will check back weekly.

**Comment by AmrEldib** [comment] 2021-02-23 18:16
Hi @andygup 
I'm with Esri Canada Technical Support, and this is an issue encountered by one of our clients
I've logged a bug for this issue, as our client needs to track it
BUG-000137647 JSAPI arcgis/core 4.18.1 in Angular 11 App Fails to Display Features added from Editor until Zooming
Could you attach this bug report to the internal bug report to make sure it can be tracked by our client
Thank you!

**Comment by andygup** [comment] 2021-02-23 19:12
@bsanti @AmrEldib can you try retesting with the latest /next version? We did implement a fix for a similar issue. Make sure to correctly set `config.assetsPath`

@bsanti I commented out [this line](https://github.com/gurgelx/ArcGIS_example/blob/master/src/app/map/map.component.ts#L32) and moved it to the first line under `init()`

```js
npm install @arcgis/core@next 
```

```js
import config from '@arcgis/core/config.js';
...

  // https://github.com/gurgelx/ArcGIS_example/blob/master/src/app/map/map.component.ts#L36
  init(): void {
    config.assetsPath = './assets';   // I'm on a Mac and this is the path I needed to use
    ...
```

**Comment by andygup** [comment] 2021-02-23 19:12
> Could you attach this bug report to the internal bug report to make sure it can be tracked by our client

@AmrEldib yes, certainly. I'll also update support on this.

**Comment by andygup** [comment] 2021-02-24 16:49
@AmrEldib let me know how the the testing goes? I did have a conversation with our tech support, they should be reaching out to you to test and hopefully close the issue.

**Comment by AmrEldib** [comment] 2021-02-25 18:16
@andygup I've tested on my end and can confirm that it's fixed now. I've also contacted the client to test on their end, but I haven't heard back. I'll let you know if an issue comes up. Thank you!

**Comment by bsanti** [comment] 2021-03-01 22:13
> @bsanti @AmrEldib can you try retesting with the latest /next version? We did implement a fix for a similar issue. Make sure to correctly set `config.assetsPath`
> 
> @bsanti I commented out [this line](https://github.com/gurgelx/ArcGIS_example/blob/master/src/app/map/map.component.ts#L32) and moved it to the first line under `init()`
> 
> ```js
> npm install @arcgis/core@next 
> ```
> 
> ```js
> import config from '@arcgis/core/config.js';
> ...
> 
>   // https://github.com/gurgelx/ArcGIS_example/blob/master/src/app/map/map.component.ts#L36
>   init(): void {
>     config.assetsPath = './assets';   // I'm on a Mac and this is the path I needed to use
>     ...
> ```
Sorry for late response @andygup  I was able to verify the fix using CDN approach.  Our use of the ESModules has been pushed back a release but I will try and verify within the next few days.

**Comment by bsanti** [comment] 2021-03-07 17:15
Just wanted to close the loop. I was able to verify the fix using ESModules.
