### ISSUE TITLE
install problem with ionic angular capacitor

### ISSUE THREAD

**Issue by losciur** [Esri/jsapi-resources#251] opened 2021-01-20 12:57 UTC
Hi,
I'm sorry, but I can't use the ES modules with a ionic angular capacitor app.
After doing:
npm install @arcgis/core

I don't know how to copy assets.

Thanks for help

**Comment by andygup** [comment] 2021-01-20 16:09
@losciur here are the instructions: https://github.com/Esri/jsapi-resources/tree/master/esm-samples/jsapi-angular-cli#arcgis-js-api-notes

**Comment by brentgti** [comment] 2021-01-20 18:29
@losciur, take a look at https://github.com/brentgti/IonicUiEsriPoc. It's an example of an ionic angular capacitor app using ES modules.

@andygup, while my example works in Android, it does NOT work on a Windows desktop using Electron. See https://community.esri.com/t5/arcgis-api-for-javascript/responsetype-image-is-not-supported-in-web-workers-or-node/m-p/1018036 for my post to ArcGIS API for JavaScript Questions about this.

**Comment by losciur** [comment] 2021-01-21 13:41
@andygup and @brentgti  thank you very much, it works!

Can I ask you about warnings?
In the terminal I found:
```
WARNING in ./node_modules/@arcgis/core/core/workers/workers.js 5:863-872
Critical dependency: the request of a dependency is an expression
    at ImportContextDependency.getWarnings (/home/losciur/programmazione/lavoro/ionic/meteoFolder/newEsri3/node_modules/webpack/lib/dependencies/ContextDependency.js:40:18)
    at Compilation.reportDependencyErrorsAndWarnings (/home/losciur/programmazione/lavoro/ionic/meteoFolder/newEsri3/node_modules/webpack/lib/Compilation.js:1454:24)
    at hooks.finishModules.callAsync.err (/home/losciur/programmazione/lavoro/ionic/meteoFolder/newEsri3/node_modules/webpack/lib/Compilation.js:1258:10)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/losciur/programmazione/lavoro/ionic/meteoFolder/newEsri3/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:42:1)
    at AsyncSeriesHook.lazyCompileHook (/home/losciur/programmazione/lavoro/ionic/meteoFolder/newEsri3/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/home/losciur/programmazione/lavoro/ionic/meteoFolder/newEsri3/node_modules/webpack/lib/Compilation.js:1253:28)
    at hooks.make.callAsync.err (/home/losciur/programmazione/lavoro/ionic/meteoFolder/newEsri3/node_modules/webpack/lib/Compiler.js:672:17)
    at _done (eval at create (/home/losciur/programmazione/lavoro/ionic/meteoFolder/newEsri3/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at _err4 (eval at create (/home/losciur/programmazione/lavoro/ionic/meteoFolder/newEsri3/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:72:22)
    at _addModuleChain (/home/losciur/programmazione/lavoro/ionic/meteoFolder/newEsri3/node_modules/webpack/lib/Compilation.js:1185:12)
    at processModuleDependencies.err (/home/losciur/programmazione/lavoro/ionic/meteoFolder/newEsri3/node_modules/webpack/lib/Compilation.js:1097:9)
    at process._tickCallback (internal/process/next_tick.js:61:11)
 @ ./node_modules/@arcgis/core/views/MapView.js
 @ ./src/app/tab1/tab1.page.ts
 @ ./src/app/tab1/tab1.module.ts
 @ ./src/app/tabs/tabs-routing.module.ts
 @ ./src/app/tabs/tabs.module.ts
 @ ./src/app/app-routing.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts

WARNING in ./node_modules/@arcgis/core/core/workers/WorkerFallback.js 5:2264-2273
Critical dependency: the request of a dependency is an expression
    at ImportContextDependency.getWarnings (/home/losciur/programmazione/lavoro/ionic/meteoFolder/newEsri3/node_modules/webpack/lib/dependencies/ContextDependency.js:40:18)
    at Compilation.reportDependencyErrorsAndWarnings (/home/losciur/programmazione/lavoro/ionic/meteoFolder/newEsri3/node_modules/webpack/lib/Compilation.js:1454:24)
    at hooks.finishModules.callAsync.err (/home/losciur/programmazione/lavoro/ionic/meteoFolder/newEsri3/node_modules/webpack/lib/Compilation.js:1258:10)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/losciur/programmazione/lavoro/ionic/meteoFolder/newEsri3/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:42:1)
    at AsyncSeriesHook.lazyCompileHook (/home/losciur/programmazione/lavoro/ionic/meteoFolder/newEsri3/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/home/losciur/programmazione/lavoro/ionic/meteoFolder/newEsri3/node_modules/webpack/lib/Compilation.js:1253:28)
    at hooks.make.callAsync.err (/home/losciur/programmazione/lavoro/ionic/meteoFolder/newEsri3/node_modules/webpack/lib/Compiler.js:672:17)
    at _done (eval at create (/home/losciur/programmazione/lavoro/ionic/meteoFolder/newEsri3/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at _err4 (eval at create (/home/losciur/programmazione/lavoro/ionic/meteoFolder/newEsri3/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:72:22)
    at _addModuleChain (/home/losciur/programmazione/lavoro/ionic/meteoFolder/newEsri3/node_modules/webpack/lib/Compilation.js:1185:12)
    at processModuleDependencies.err (/home/losciur/programmazione/lavoro/ionic/meteoFolder/newEsri3/node_modules/webpack/lib/Compilation.js:1097:9)
    at process._tickCallback (internal/process/next_tick.js:61:11)
 @ ./node_modules/@arcgis/core/core/workers/workerFactory.js
 @ ./node_modules/@arcgis/core/core/workers/WorkerOwner.js
 @ ./node_modules/@arcgis/core/core/workers/workers.js
 @ ./node_modules/@arcgis/core/views/MapView.js
 @ ./src/app/tab1/tab1.page.ts
 @ ./src/app/tab1/tab1.module.ts
 @ ./src/app/tabs/tabs-routing.module.ts
 @ ./src/app/tabs/tabs.module.ts
 @ ./src/app/app-routing.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts

```

And in Chrromium Dev Tools I have:
![immagine](https://user-images.githubusercontent.com/62714342/105358404-6afd4e00-5bf6-11eb-8531-4320a921c149.png)

Thanks very much for helping

**Comment by andygup** [comment] 2021-01-21 16:02
@losciur the critical dependency warnings are something we are aware of and hope to fix at some point, those warnings are related to legacy code that we haven't been able to replace yet.

For the source map warnings, I haven't seen those in a while. Are you seeing them in a dev build or a production build? For production builds you can set `configurations.production.sourceMaps` to `true`.

**Comment by brentgti** [comment] 2021-01-21 16:59
@andygup, Thanks for the suggestion. How do I set `configurations.production.sourceMaps` to `true`?

**Comment by andygup** [comment] 2021-01-21 17:04
@brentgti Oh, oops forgot to mention the filename, you set that in `angular.json`. 

![image](https://user-images.githubusercontent.com/510440/105384999-17780980-5bd0-11eb-8cd6-edcd513f52e8.png)

**Comment by brentgti** [comment] 2021-01-21 17:55
@andygup, thanks for the additional information. I'm still seeing the problem with that setting changed. I honestly don't know if I'm doing a production build. I build using this command: `ionic build && npx cap copy @capacitor-community/electron` and run using `npx cap open @capacitor-community/electron`.

**Comment by andygup** [comment] 2021-01-21 18:35
Yep that's a production build. Using `build` compiles all your assets for production deployment. FYI, this isn't an ArcGIS issue, it's an issue between Angular and Chrome. 

A couple other thoughts:
* Try using the `--prod` option, for example `ionic build --prod`. 
* You can also try changing your Chrome dev settings. If you internet search on "DevTools failed to load sourceMap" there are a bunch of suggestions.

Since you got it working, I'm going to go ahead and close this issue.

**Closed by andygup** 2021-01-21 18:35 UTC

**Comment by brentgti** [comment] 2021-01-21 18:38
Well, @andygup, @losciur got his problem resolved, I think, but I still don't see a map in my app when I run on the desktop, unless it's a vector map--images still aren't loading. If I need to create another issue or do something else somewhere else, please let me know.

**Comment by andygup** [comment] 2021-01-21 18:40
@brentgti yes, please open a separate issue for the map and images not loading. Also include any console errors and if possible a repo or stackblitz so we can reproduce the issue.
